# Generated by Django 5.1.3 on 2024-11-07 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messaging', '0001_initial'),
        ('notifications', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread_messages', models.ManyToManyField(blank=True, to='messaging.message')),
                ('unread_notifications', models.ManyToManyField(blank=True, to='notifications.notification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inbox', to='user.user')),
            ],
        ),
    ]
